/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendOtpRouteRouteImport } from './routes/send-otp/route'
import { Route as PaymentRouteRouteImport } from './routes/payment/route'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as HomepageRouteRouteImport } from './routes/_homepage/route'
import { Route as SendOtpIndexRouteImport } from './routes/send-otp/index'
import { Route as PaymentIndexRouteImport } from './routes/payment/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as HomepageIndexRouteImport } from './routes/_homepage/index'
import { Route as HomepageOrganicHoneyIndexRouteImport } from './routes/_homepage/organic-honey/index'
import { Route as HomepageOffersIndexRouteImport } from './routes/_homepage/offers/index'
import { Route as HomepageMnNhnIndexRouteImport } from './routes/_homepage/mn-nhn/index'
import { Route as HomepageHoneyMixturesIndexRouteImport } from './routes/_homepage/honey-mixtures/index'
import { Route as HomepageHiveProductsIndexRouteImport } from './routes/_homepage/hive-products/index'
import { Route as HomepageFarmProductsIndexRouteImport } from './routes/_homepage/farm-products/index'
import { Route as HomepageContactUsIndexRouteImport } from './routes/_homepage/contact-us/index'
import { Route as HomepageCategoriesIndexRouteImport } from './routes/_homepage/categories/index'
import { Route as HomepageCartIndexRouteImport } from './routes/_homepage/cart/index'
import { Route as HomepageSlugIndexRouteImport } from './routes/_homepage/$slug/index'

const SendOtpRouteRoute = SendOtpRouteRouteImport.update({
  id: '/send-otp',
  path: '/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRouteRoute = PaymentRouteRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRouteRoute = HomepageRouteRouteImport.update({
  id: '/_homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const SendOtpIndexRoute = SendOtpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SendOtpRouteRoute,
} as any)
const PaymentIndexRoute = PaymentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaymentRouteRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const HomepageIndexRoute = HomepageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomepageRouteRoute,
} as any)
const HomepageOrganicHoneyIndexRoute =
  HomepageOrganicHoneyIndexRouteImport.update({
    id: '/organic-honey/',
    path: '/organic-honey/',
    getParentRoute: () => HomepageRouteRoute,
  } as any)
const HomepageOffersIndexRoute = HomepageOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => HomepageRouteRoute,
} as any)
const HomepageMnNhnIndexRoute = HomepageMnNhnIndexRouteImport.update({
  id: '/mn-nhn/',
  path: '/mn-nhn/',
  getParentRoute: () => HomepageRouteRoute,
} as any)
const HomepageHoneyMixturesIndexRoute =
  HomepageHoneyMixturesIndexRouteImport.update({
    id: '/honey-mixtures/',
    path: '/honey-mixtures/',
    getParentRoute: () => HomepageRouteRoute,
  } as any)
const HomepageHiveProductsIndexRoute =
  HomepageHiveProductsIndexRouteImport.update({
    id: '/hive-products/',
    path: '/hive-products/',
    getParentRoute: () => HomepageRouteRoute,
  } as any)
const HomepageFarmProductsIndexRoute =
  HomepageFarmProductsIndexRouteImport.update({
    id: '/farm-products/',
    path: '/farm-products/',
    getParentRoute: () => HomepageRouteRoute,
  } as any)
const HomepageContactUsIndexRoute = HomepageContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => HomepageRouteRoute,
} as any)
const HomepageCategoriesIndexRoute = HomepageCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => HomepageRouteRoute,
} as any)
const HomepageCartIndexRoute = HomepageCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => HomepageRouteRoute,
} as any)
const HomepageSlugIndexRoute = HomepageSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => HomepageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomepageIndexRoute
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/payment': typeof PaymentRouteRouteWithChildren
  '/send-otp': typeof SendOtpRouteRouteWithChildren
  '/checkout/': typeof CheckoutIndexRoute
  '/payment/': typeof PaymentIndexRoute
  '/send-otp/': typeof SendOtpIndexRoute
  '/$slug/': typeof HomepageSlugIndexRoute
  '/cart/': typeof HomepageCartIndexRoute
  '/categories/': typeof HomepageCategoriesIndexRoute
  '/contact-us/': typeof HomepageContactUsIndexRoute
  '/farm-products/': typeof HomepageFarmProductsIndexRoute
  '/hive-products/': typeof HomepageHiveProductsIndexRoute
  '/honey-mixtures/': typeof HomepageHoneyMixturesIndexRoute
  '/mn-nhn/': typeof HomepageMnNhnIndexRoute
  '/offers/': typeof HomepageOffersIndexRoute
  '/organic-honey/': typeof HomepageOrganicHoneyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomepageIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/payment': typeof PaymentIndexRoute
  '/send-otp': typeof SendOtpIndexRoute
  '/$slug': typeof HomepageSlugIndexRoute
  '/cart': typeof HomepageCartIndexRoute
  '/categories': typeof HomepageCategoriesIndexRoute
  '/contact-us': typeof HomepageContactUsIndexRoute
  '/farm-products': typeof HomepageFarmProductsIndexRoute
  '/hive-products': typeof HomepageHiveProductsIndexRoute
  '/honey-mixtures': typeof HomepageHoneyMixturesIndexRoute
  '/mn-nhn': typeof HomepageMnNhnIndexRoute
  '/offers': typeof HomepageOffersIndexRoute
  '/organic-honey': typeof HomepageOrganicHoneyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homepage': typeof HomepageRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/payment': typeof PaymentRouteRouteWithChildren
  '/send-otp': typeof SendOtpRouteRouteWithChildren
  '/_homepage/': typeof HomepageIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/payment/': typeof PaymentIndexRoute
  '/send-otp/': typeof SendOtpIndexRoute
  '/_homepage/$slug/': typeof HomepageSlugIndexRoute
  '/_homepage/cart/': typeof HomepageCartIndexRoute
  '/_homepage/categories/': typeof HomepageCategoriesIndexRoute
  '/_homepage/contact-us/': typeof HomepageContactUsIndexRoute
  '/_homepage/farm-products/': typeof HomepageFarmProductsIndexRoute
  '/_homepage/hive-products/': typeof HomepageHiveProductsIndexRoute
  '/_homepage/honey-mixtures/': typeof HomepageHoneyMixturesIndexRoute
  '/_homepage/mn-nhn/': typeof HomepageMnNhnIndexRoute
  '/_homepage/offers/': typeof HomepageOffersIndexRoute
  '/_homepage/organic-honey/': typeof HomepageOrganicHoneyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/payment'
    | '/send-otp'
    | '/checkout/'
    | '/payment/'
    | '/send-otp/'
    | '/$slug/'
    | '/cart/'
    | '/categories/'
    | '/contact-us/'
    | '/farm-products/'
    | '/hive-products/'
    | '/honey-mixtures/'
    | '/mn-nhn/'
    | '/offers/'
    | '/organic-honey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/payment'
    | '/send-otp'
    | '/$slug'
    | '/cart'
    | '/categories'
    | '/contact-us'
    | '/farm-products'
    | '/hive-products'
    | '/honey-mixtures'
    | '/mn-nhn'
    | '/offers'
    | '/organic-honey'
  id:
    | '__root__'
    | '/_homepage'
    | '/checkout'
    | '/payment'
    | '/send-otp'
    | '/_homepage/'
    | '/checkout/'
    | '/payment/'
    | '/send-otp/'
    | '/_homepage/$slug/'
    | '/_homepage/cart/'
    | '/_homepage/categories/'
    | '/_homepage/contact-us/'
    | '/_homepage/farm-products/'
    | '/_homepage/hive-products/'
    | '/_homepage/honey-mixtures/'
    | '/_homepage/mn-nhn/'
    | '/_homepage/offers/'
    | '/_homepage/organic-honey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomepageRouteRoute: typeof HomepageRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  PaymentRouteRoute: typeof PaymentRouteRouteWithChildren
  SendOtpRouteRoute: typeof SendOtpRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send-otp': {
      id: '/send-otp'
      path: '/send-otp'
      fullPath: '/send-otp'
      preLoaderRoute: typeof SendOtpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homepage': {
      id: '/_homepage'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomepageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-otp/': {
      id: '/send-otp/'
      path: '/'
      fullPath: '/send-otp/'
      preLoaderRoute: typeof SendOtpIndexRouteImport
      parentRoute: typeof SendOtpRouteRoute
    }
    '/payment/': {
      id: '/payment/'
      path: '/'
      fullPath: '/payment/'
      preLoaderRoute: typeof PaymentIndexRouteImport
      parentRoute: typeof PaymentRouteRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/_homepage/': {
      id: '/_homepage/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomepageIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/organic-honey/': {
      id: '/_homepage/organic-honey/'
      path: '/organic-honey'
      fullPath: '/organic-honey/'
      preLoaderRoute: typeof HomepageOrganicHoneyIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/offers/': {
      id: '/_homepage/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof HomepageOffersIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/mn-nhn/': {
      id: '/_homepage/mn-nhn/'
      path: '/mn-nhn'
      fullPath: '/mn-nhn/'
      preLoaderRoute: typeof HomepageMnNhnIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/honey-mixtures/': {
      id: '/_homepage/honey-mixtures/'
      path: '/honey-mixtures'
      fullPath: '/honey-mixtures/'
      preLoaderRoute: typeof HomepageHoneyMixturesIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/hive-products/': {
      id: '/_homepage/hive-products/'
      path: '/hive-products'
      fullPath: '/hive-products/'
      preLoaderRoute: typeof HomepageHiveProductsIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/farm-products/': {
      id: '/_homepage/farm-products/'
      path: '/farm-products'
      fullPath: '/farm-products/'
      preLoaderRoute: typeof HomepageFarmProductsIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/contact-us/': {
      id: '/_homepage/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof HomepageContactUsIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/categories/': {
      id: '/_homepage/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof HomepageCategoriesIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/cart/': {
      id: '/_homepage/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof HomepageCartIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
    '/_homepage/$slug/': {
      id: '/_homepage/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof HomepageSlugIndexRouteImport
      parentRoute: typeof HomepageRouteRoute
    }
  }
}

interface HomepageRouteRouteChildren {
  HomepageIndexRoute: typeof HomepageIndexRoute
  HomepageSlugIndexRoute: typeof HomepageSlugIndexRoute
  HomepageCartIndexRoute: typeof HomepageCartIndexRoute
  HomepageCategoriesIndexRoute: typeof HomepageCategoriesIndexRoute
  HomepageContactUsIndexRoute: typeof HomepageContactUsIndexRoute
  HomepageFarmProductsIndexRoute: typeof HomepageFarmProductsIndexRoute
  HomepageHiveProductsIndexRoute: typeof HomepageHiveProductsIndexRoute
  HomepageHoneyMixturesIndexRoute: typeof HomepageHoneyMixturesIndexRoute
  HomepageMnNhnIndexRoute: typeof HomepageMnNhnIndexRoute
  HomepageOffersIndexRoute: typeof HomepageOffersIndexRoute
  HomepageOrganicHoneyIndexRoute: typeof HomepageOrganicHoneyIndexRoute
}

const HomepageRouteRouteChildren: HomepageRouteRouteChildren = {
  HomepageIndexRoute: HomepageIndexRoute,
  HomepageSlugIndexRoute: HomepageSlugIndexRoute,
  HomepageCartIndexRoute: HomepageCartIndexRoute,
  HomepageCategoriesIndexRoute: HomepageCategoriesIndexRoute,
  HomepageContactUsIndexRoute: HomepageContactUsIndexRoute,
  HomepageFarmProductsIndexRoute: HomepageFarmProductsIndexRoute,
  HomepageHiveProductsIndexRoute: HomepageHiveProductsIndexRoute,
  HomepageHoneyMixturesIndexRoute: HomepageHoneyMixturesIndexRoute,
  HomepageMnNhnIndexRoute: HomepageMnNhnIndexRoute,
  HomepageOffersIndexRoute: HomepageOffersIndexRoute,
  HomepageOrganicHoneyIndexRoute: HomepageOrganicHoneyIndexRoute,
}

const HomepageRouteRouteWithChildren = HomepageRouteRoute._addFileChildren(
  HomepageRouteRouteChildren,
)

interface CheckoutRouteRouteChildren {
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface PaymentRouteRouteChildren {
  PaymentIndexRoute: typeof PaymentIndexRoute
}

const PaymentRouteRouteChildren: PaymentRouteRouteChildren = {
  PaymentIndexRoute: PaymentIndexRoute,
}

const PaymentRouteRouteWithChildren = PaymentRouteRoute._addFileChildren(
  PaymentRouteRouteChildren,
)

interface SendOtpRouteRouteChildren {
  SendOtpIndexRoute: typeof SendOtpIndexRoute
}

const SendOtpRouteRouteChildren: SendOtpRouteRouteChildren = {
  SendOtpIndexRoute: SendOtpIndexRoute,
}

const SendOtpRouteRouteWithChildren = SendOtpRouteRoute._addFileChildren(
  SendOtpRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomepageRouteRoute: HomepageRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  PaymentRouteRoute: PaymentRouteRouteWithChildren,
  SendOtpRouteRoute: SendOtpRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
